version: '3.3'

networks:
  grafana-network:
    external: true 

volumes:
  prometheus_data:
  grafana_data:
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    labels:
        application: "Prometheus"
    volumes:
      - ./prometheus-setup/prometheus.yml:/etc/prometheus/prometheus.yml 
      - prometheus_data:/prometheus
    networks:
        - grafana-network
    ports:
        - "9090:9090"
  grafana:
    container_name: grafana
    labels:
        application: "Grafana"
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
        - grafana-network
    ports:
        - "3000:3000"